version: '1.0'

services:
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    volumes:
      - .:/home/djproj
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_completed_successfully
  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: mysql
    env_file:
      - ./db_config.env
    volumes:
      - mysqldata:/var/lib/mysql
    

volumes:
  mysqldata: